import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RequestProvider from "./components/RequestContext";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul className="flex flex-wrap bg-green-300">
            <Link
              href={"/dashboard"}
              className="p-2 hover:bg-green-400 hover:font-bold active:bg-green-600"
            >
              Dashboard
            </Link>
            <Link
              href={"/pick-and-dispatch"}
              className="p-2 hover:bg-green-400 hover:font-bold active:bg-green-600"
            >
              Pick and Dispatch
            </Link>
            <Link
              href={"/create-request"}
              className="p-2 hover:bg-green-400 hover:font-bold active:bg-green-600"
            >
              Create a new request
            </Link>
            <Link
              href={"/upload-skus"}
              className="p-2 hover:bg-green-400 hover:font-bold active:bg-green-600"
            >
              Upload Skus
            </Link>
          </ul>
        </nav>
        <RequestProvider>{children}</RequestProvider>
      </body>
    </html>
  );
}
